# Generated by Django 3.0.4 on 2020-05-20 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='account_type',
            field=models.CharField(choices=[('Select', 'Select'), ('Tutor', 'Tutor'), ('Student', 'Student')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_over',
            field=models.TextField(max_length=3000, null=True),
        ),
    ]
